version: "3.7"
services:
        apache-server:
                build:
                        context: ./apache-server
                volumes: 
                        - "./html/:/var/www/html/"
                ports: 
                        - "80:80"
                links:
                        - 'mysql-server'

        mysql-server: 
                build:
                        context: ./mysql-server
                volumes:
                        - mysql_data:/var/lib/mysql

        phpmyadmin:
                image: phpmyadmin/phpmyadmin:5.0.2
                environment:
                        PMA_HOST: mysql-server
                        PMA_USER: root
                        PMA_PASSWORD: rootpass
                ports:
                        - "5000:80"
volumes:
        mysql_data:

